### ISSUE TITLE
Error during installation Python >=3.5

### ISSUE THREAD

**Issue by rafaeltiveron** [macmanes-lab/Oyster_River_Protocol#33]
```
Downloading/unpacking scipy
  Downloading scipy-1.3.1.tar.gz (23.6MB): 23.6MB downloaded
  Running setup.py (path:/tmp/pip_build_rafael/scipy/setup.py) egg_info for package scipy
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip_build_rafael/scipy/setup.py", line 31, in <module>
        raise RuntimeError("Python version >= 3.5 required.")
    RuntimeError: Python version >= 3.5 required.
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip_build_rafael/scipy/setup.py", line 31, in <module>

    raise RuntimeError("Python version >= 3.5 required.")

RuntimeError: Python version >= 3.5 required.

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_rafael/scipy
Storing debug log for failure in /home/rafael/.pip/pip.log
```

Installation is redirecting to Python 2.7 from system and not using Python just inside conda.

**Comment by alanorth** [comment]
Short answer, [upgrade pip](https://stackoverflow.com/questions/26575587/cant-install-scipy-through-pip#26964891):

```
$ pip2 install --upgrade pip
```

Long answer: If you are manually installing ORP then you might have issues following the installation instructions because the version of Python in the Dockerfile is Python 2. You need to make sure your pip2 version is new enough to support smart installation using wheel packages.
